CableChat/config/routes.rb
Rails.application.routes.draw do

  resources :chatrooms, only: [:index, :new, :create, :show]
  mount ActionCable.server => "/cable"

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

CableChat/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

CableChat/app/models/chatroom.rb
class Chatroom < ApplicationRecord
  belongs_to :user
  has_many :messages, dependent: :destroy
end

CableChat/app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :chatroom

  validates :body, presence: true, length: {minimum: 2, maximum: 1000}

  after_create_commit { MessageBroadcastJob.perform_later(self) }
end

CableChat/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :chatrooms, dependent: :destroy
  has_many :messages, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def name
    email.split("@")[0]
  end

  def timestamp
    created_at.strftime('%H:%M:%S: %d %B %Y')
  end

end

CableChat/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

CableChat/app/controllers/chatrooms_controller.rb
class ChatroomsController < ApplicationController

  def index
    @chatrooms = Chatroom.all
  end

  def new
    @chatroom = Chatroom.new
    # binding.pry
  end

  def create
    # binding.pry
    @chatroom = current_user.chatrooms.build(chatroom_params)
    if @chatroom.save
      flash[:success] = 'Chat room added'
      redirect_to chatrooms_path
    else
      render 'new'
    end
  end

  def show
    @chatroom = Chatroom.includes(:messages).find_by(id: params[:id])
    @message = Message.new
  end

  private

  def chatroom_params
    params.require(:chatroom).permit(:title)
  end
end

CableChat/app/controllers/messages_controller.rb
class MessagesController < ApplicationController

end

CableChat/app/helpers/application_helper.rb
module ApplicationHelper

  def gravatar_for(user, opt={})
    opts[:alt] = user.name
    image_tag "https://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(user.email)}?s=#{opts.delete(:size) { 40 }}", opts
  end

end

CableChat/app/helpers/chatrooms_helper.rb
module ChatroomsHelper
end

CableChat/app/helpers/messages_helper.rb
module MessagesHelper
end

CableChat/app/views/chatrooms/_chatroom.html.erb
<li><%= link_to "Enter #{chatroom.title}", chatroom_path(chatroom) %></li>

CableChat/app/views/chatrooms/index.html.erb
<h1>Chatrooms</h1>

<p class="lead">
  <%= link_to 'new chat room', new_chatroom_path, class: "btn btn-primary" %>
</p>

<h1>here are your previous chats with Duckly</h1>

<ul>
  <%= render @chatrooms %>
</ul>

CableChat/app/views/chatrooms/new.html.erb
<h1>Add chat room</h1>

<%= form_for @chatroom do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, autofocus: true, class: 'form-control' %>
  </div>

  <%= f.submit "Add!", class: 'btn btn-primary' %>
<% end %>

CableChat/app/views/chatrooms/show.html.erb
<h1><%= @chatroom.title %></h1>

<div id="messages" data-chatroom-id="<%= @chatroom.id %>">
  <%= render @chatroom.messages %>
</div>



<%= form_for @message, url: '#' do |f| %>
  <input type="hidden" id="chatroom" data-id="<%= @chatroom.id %>">
  <div class="form-group">
    <%= f.label :body %>
    <%= f.text_area :body, class: 'form-control' %>
    <small class="text-muted">From 2 to 1000 characters</small>
  </div>

  <%= f.submit "Post", class: 'btn btn-primary btn-lg' %>
<% end %>

CableChat/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CableChat</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

CableChat/app/views/messages/_message.html.erb
<div class="card">
  <div class="card-block">
    <div class="row">
      <div class="col-md-1">
      </div>
      <div class="col-md-11">
        <p class="card-text">
          <span class="text-muted"><%= message.user.name %> says</span><br>
          <%= message.body %>
        </p>
      </div>
    </div>
  </div>
</div>